#!/usr/bin/env python3
"""FSI on the spectator alpha of the 6Li alpha-tag, as a REWEIGHTING.

Cosyn-Weiss deuteron FSI (PRC 97:035209 / PRC 102:065204) transplanted to
X-alpha scattering.  The whole model is one line of physics:

    Psi_FSI(alpha_s, kT)  =  psi(alpha_s, kT)
                             - int d^2k'T/(2pi)^2  Gtil(kT - k'T) psi(alpha_s, k'T)

    Gtil(q) = (sigma_Xa (1 - i eps) / 2) exp(-B_a q^2 / 2)          [GeV^-2]

which is the momentum-space form of the Glauber statement
Psi_FSI(b) = psi(b) [1 - Gamma(b)] with the profile

    Gamma(b) = (sigma_Xa (1 - i eps) / (4 pi B_a)) exp(-b^2 / (2 B_a)) ,

so Gtil(q) = int d^2b e^{i q.b} Gamma(b) and Gtil(0) = sigma_Xa (1 - i eps)/2.

Two facts fix the structure:
  * at EIC energies the rescattering is EIKONAL: it transfers transverse
    momentum only, so the spectator light-cone fraction alpha_s (equivalently
    k_z in the ion rest frame) is a spectator of the FSI too.  The convolution
    is 2-D, at fixed k_z.  This is why the FSI/IA ratio is ~1 at
    theta_k -> 0, pi and deviates most near theta_k = 90 deg.
  * the longitudinal integral over the rescattering propagator has been done
    by residue (on-shell / pole part); the principal-value (off-shell) piece
    is O(Delta/k) with Delta = (W'^2 - W^2)/(2 nu) -> 0 at large nu and is
    DROPPED here.  That is the approximation this model stands on.

The X-alpha profile is built by Glauber from the X-N one, so sigma_Xa is
NOT 4 sigma_XN but the shadowed 4 sigma_XN(1 - ...), and the slope B_a is
generated by the alpha's own size rather than assumed.

Reference numbers this file prints are in the report.
"""

import numpy as np

# ----------------------------------------------------------------- units
GEV_FM = 0.1973269804          # hbar c [GeV fm]
MB_GEV2 = 1.0 / 0.3893793      # 1 mb = 2.5682 GeV^-2

# ------------------------------------------------------- 6Li alpha-d w.f.
M_ALPHA = 3.72738              # GeV, AME2020 nuclear mass
M_D = 1.875613
S_ALPHA_D = 1.4743e-3          # GeV, 6Li -> alpha + d separation energy
BETA = 0.30                    # GeV, LiPolGen BETA_DEFAULT


def kappa_alpha_d():
    mu = M_ALPHA * M_D / (M_ALPHA + M_D)
    return np.sqrt(2.0 * mu * S_ALPHA_D)


def psi_hulthen(k, kappa=None, beta=BETA):
    """Unnormalized S-wave Hulthen psi(k) -- LiPolGen cluster.hpp L=0."""
    if kappa is None:
        kappa = kappa_alpha_d()
    return 1.0 / (k**2 + kappa**2) - 1.0 / (k**2 + beta**2)


# --------------------------------------------------- X-alpha Glauber profile
def alpha_transverse_density_a2():
    """a^2 [fm^2] of the alpha POINT-nucleon Gaussian density.

    r_ch(4He) = 1.6755 fm, r_ch(p) = 0.8409 fm (CODATA/PRad-era)
    r_pt^2 = r_ch^2(alpha) - r_ch^2(p)  ->  a^2 = r_pt^2 / 3 for
    rho ~ exp(-r^2 / 2a^2), T(s) = (1/2 pi a^2) exp(-s^2 / 2a^2).
    """
    r_pt2 = 1.6755**2 - 0.8409**2
    return r_pt2 / 3.0


def gamma_alpha_b(b_fm, sigma_XN_mb, eps, B_N_gev2):
    """Glauber profile of X on the alpha at impact parameter b [fm].

    Gamma_a(b) = 1 - [1 - (Gamma_N conv T_a)(b)]^4,
    Gamma_N(b) = (sigma (1 - i eps) / (4 pi B_N)) exp(-b^2 / 2 B_N).
    Both Gaussians, so the convolution with T_a is analytic: the widths add.
    """
    B_N_fm2 = B_N_gev2 * GEV_FM**2
    a2 = alpha_transverse_density_a2()
    w2 = B_N_fm2 + a2                       # convolved Gaussian width^2 [fm^2]
    sig_fm2 = sigma_XN_mb * 0.1             # 1 mb = 0.1 fm^2
    # (Gamma_N conv T_a)(b), normalisation preserved: int d^2b = sigma(1-i eps)/2
    g1 = (sig_fm2 * (1.0 - 1j * eps) / (4.0 * np.pi * w2)) * np.exp(
        -b_fm**2 / (2.0 * w2))
    return 1.0 - (1.0 - g1) ** 4


def gtilde_alpha(q_gev, sigma_XN_mb, eps=-0.5, B_N_gev2=6.0, nb=2000,
                 b_max_fm=12.0):
    """Gtil_a(q) = int d^2b e^{i q.b} Gamma_a(b)  [GeV^-2], q in GeV.

    Done as a 2-D Hankel transform (azimuthally symmetric):
    Gtil(q) = 2 pi int b db J0(q b) Gamma_a(b).
    """
    from scipy.special import j0
    b = np.linspace(1e-6, b_max_fm, nb)
    g = gamma_alpha_b(b, sigma_XN_mb, eps, B_N_gev2)
    q = np.atleast_1d(q_gev)
    # b [fm] * q [GeV] -> dimensionless needs q b / GEV_FM
    arg = np.outer(q / GEV_FM, b)
    integ = 2.0 * np.pi * np.trapz(b[None, :] * j0(arg) * g[None, :], b, axis=1)
    return integ / GEV_FM**2         # fm^2 -> GeV^-2


def sigma_eff_alpha(sigma_XN_mb, eps=-0.5, B_N_gev2=6.0):
    """sigma_Xa = 2 Re int d^2b Gamma_a(b) = 2 Re Gtil_a(0)  [mb]."""
    g0 = gtilde_alpha(np.array([0.0]), sigma_XN_mb, eps, B_N_gev2)[0]
    return 2.0 * np.real(g0) / MB_GEV2


def slope_eff_alpha(sigma_XN_mb, eps=-0.5, B_N_gev2=6.0):
    """Effective slope B_a from -2 dln|Gtil|/dq^2 at q -> 0 [GeV^-2]."""
    q = np.array([0.0, 0.05, 0.10])
    g = np.abs(gtilde_alpha(q, sigma_XN_mb, eps, B_N_gev2))
    return -2.0 * np.log(g[1] / g[0]) / q[1] ** 2


# ------------------------------------------------------ the FSI convolution
def _gtilde_table(sigma_XN_mb, eps, B_N_gev2, q_hi=4.0, nq_tab=400):
    """Gtil_a(q) tabulated once on [0, q_hi] and returned as an interpolator."""
    qs = np.linspace(0.0, q_hi, nq_tab)
    gs = gtilde_alpha(qs, sigma_XN_mb, eps, B_N_gev2)

    def interp(q):
        qq = np.clip(q, 0.0, q_hi)
        return np.interp(qq, qs, gs.real) + 1j * np.interp(qq, qs, gs.imag)

    return interp


def fsi_ratio_grid(k_vals, cos_vals, sigma_XN_mb=40.0, eps=-0.5,
                   B_N_gev2=6.0, nq=241, q_max=1.5):
    """|Psi_FSI|^2 / |psi|^2 on the (k, cos theta_k) grid.

    theta_k is measured from the VIRTUAL-PHOTON (+z) direction in the ion rest
    frame, so k_z = k cos(theta), kT = k sin(theta).  The FSI convolution is
    2-D at FIXED k_z (eikonal), which is why the ratio -> 1 at theta -> 0, pi.
    """
    gt_of = _gtilde_table(sigma_XN_mb, eps, B_N_gev2)
    ax = np.linspace(-q_max, q_max, nq)
    dq = ax[1] - ax[0]
    KX, KY = np.meshgrid(ax, ax, indexing="ij")

    out = np.zeros((len(k_vals), len(cos_vals)))
    for ic, c in enumerate(cos_vals):
        s = np.sqrt(max(0.0, 1.0 - c * c))
        for ik, k in enumerate(k_vals):
            kz, kTx = k * c, k * s
            psi_p = psi_hulthen(np.sqrt(kz**2 + KX**2 + KY**2))
            gt = gt_of(np.sqrt((kTx - KX) ** 2 + KY**2))
            corr = np.sum(gt * psi_p) * dq * dq / (2.0 * np.pi) ** 2
            psi0 = psi_hulthen(k)
            out[ik, ic] = abs(psi0 - corr) ** 2 / psi0**2
    return out



def fsi_ratio_kt(kz_vals, kt_vals, sigma_XN_mb=40.0, eps=-0.5, B_N_gev2=6.0,
                 nq=241, q_max=1.5):
    """The same ratio, but on the (k_z, k_T) grid the FSI actually depends on.

    The eikonal kernel is a function of k_T alone, so this is the natural
    variable: the Roman-Pot alpha tag selects SMALL p_T, i.e. small k_T, which
    is exactly the FSI-suppressed corner.
    """
    gt_of = _gtilde_table(sigma_XN_mb, eps, B_N_gev2)
    ax = np.linspace(-q_max, q_max, nq)
    dq = ax[1] - ax[0]
    KX, KY = np.meshgrid(ax, ax, indexing="ij")
    out = np.zeros((len(kz_vals), len(kt_vals)))
    for iz, kz in enumerate(kz_vals):
        psi_p = psi_hulthen(np.sqrt(kz**2 + KX**2 + KY**2))
        for it, kt in enumerate(kt_vals):
            gt = gt_of(np.sqrt((kt - KX) ** 2 + KY**2))
            corr = np.sum(gt * psi_p) * dq * dq / (2.0 * np.pi) ** 2
            psi0 = psi_hulthen(np.hypot(kz, kt))
            out[iz, it] = abs(psi0 - corr) ** 2 / psi0**2
    return out


def delta_longitudinal(k_gev, m_spec=M_ALPHA):
    """The GEA longitudinal momentum transfer this model DROPS, for scale.

    The spectator stays on shell before and after the rescattering and the X
    system is coherent (its mass does not change), so
        Delta ~ [E_a(k\') - E_a(k)] / v_X  ~  (k\'^2 - k^2) / (2 m_a).
    Compare it to kappa = 60.7 MeV: when Delta << kappa the eikonal (Delta = 0)
    limit is good and the FSI kernel is a function of k_T alone, which is why
    the ratio comes out symmetric under theta -> pi - theta.
    """
    return k_gev**2 / (2.0 * m_spec)


def main():
    kappa = kappa_alpha_d()
    print(f"# 6Li alpha-d:  kappa = {kappa*1e3:.2f} MeV,  beta = {BETA} GeV")
    print(f"# alpha point-density a^2 = {alpha_transverse_density_a2():.4f} fm^2"
          f"  (a = {np.sqrt(alpha_transverse_density_a2()):.3f} fm)")
    print()
    print("# X-alpha Glauber profile, eps = -0.5, B_XN = 6 GeV^-2")
    print(f"# {'sig_XN[mb]':>11} {'sig_Xa[mb]':>11} {'4 sig_XN':>10} "
          f"{'shadowing':>10} {'B_a[GeV^-2]':>12}")
    for s in (10.0, 20.0, 30.0, 40.0, 50.0):
        se = sigma_eff_alpha(s)
        print(f"  {s:11.1f} {se:11.2f} {4*s:10.1f} {se/(4*s):10.3f} "
              f"{slope_eff_alpha(s):12.2f}")
    print()

    k_vals = np.array([0.02, 0.05, 0.10, 0.15, 0.20, 0.30, 0.40])
    cos_vals = np.array([1.0, 0.866, 0.5, 0.0, -0.5, -0.866, -1.0])
    for sig in (40.0, 20.0):
        print(f"# FSI/IA ratio, sigma_XN = {sig:.0f} mb, eps = -0.5, "
              f"B_XN = 6 GeV^-2  (W ~ 10 GeV)")
        hdr = "  " + f"{'k[GeV]':>8}" + "".join(
            f"{'th=' + str(int(round(np.degrees(np.arccos(c))))):>9}"
            for c in cos_vals)
        print(hdr)
        r = fsi_ratio_grid(k_vals, cos_vals, sigma_XN_mb=sig)
        for ik, k in enumerate(k_vals):
            print("  " + f"{k:8.3f}" + "".join(f"{v:9.4f}" for v in r[ik]))
        print()

    print("# FSI/IA on the (k_z, k_T) grid -- the variables the eikonal "
          "kernel actually uses, sigma_XN = 40 mb")
    kz_vals = np.array([0.0, 0.05, 0.10, 0.20, 0.30])
    kt_vals = np.array([0.0, 0.02, 0.05, 0.08, 0.12, 0.20, 0.30])
    r = fsi_ratio_kt(kz_vals, kt_vals, sigma_XN_mb=40.0)
    print("  " + "   kz.kT" + "".join(f"{t:9.2f}" for t in kt_vals))
    for iz, kz in enumerate(kz_vals):
        print("  " + f"{kz:8.2f}" + "".join(f"{v:9.4f}" for v in r[iz]))
    print()
    print("# dropped GEA longitudinal transfer Delta = k^2 / (2 m_alpha), "
          "vs kappa = %.1f MeV" % (kappa_alpha_d() * 1e3))
    for k in (0.05, 0.1, 0.2, 0.3):
        print(f"    k = {k:.2f} GeV  ->  Delta = "
              f"{delta_longitudinal(k)*1e3:6.2f} MeV")


if __name__ == "__main__":
    main()
